version: "3.5"
services:
  mev-boost:
    build:
      context: build
      args:
        UPSTREAM_VERSION: v0.7.8
    volumes:
      - "data:/var/lib/mev-boost"
    environment:
      NETWORK: ""
      RELAYS: ""
    image: "mev-boost.mev-boost-goerli.dnp.dappnode.eth:0.1.0"
    restart: unless-stopped
volumes:
  data: {}
