version: "3.5"
services:
  mev-boost:
    build:
      context: src
      args:
        UPSTREAM_VERSION: v1.6
    volumes:
      - "data:/var/lib/mev-boost"
    environment:
      RELAYS: ""
      EXTRA_OPTS: ""
    image: "mev-boost.mev-boost-goerli.dnp.dappnode.eth:0.1.0"
    restart: unless-stopped
volumes:
  data: {}
